import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — Fillyfy',
  description: 'Terms and conditions for using the Fillyfy service.',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gray-950 text-white px-6 py-20">
      <div className="mx-auto max-w-3xl">
        <h1 className="text-4xl font-bold">Terms of Service</h1>
        <p className="mt-2 text-gray-400">Last updated: June 2025</p>

        <div className="mt-12 space-y-10 text-gray-300 leading-7">
          <section>
            <h2 className="text-xl font-semibold text-white">Acceptable Use</h2>
            <p className="mt-3">
              You agree to use Fillyfy only for its intended purpose: receiving AI-powered explanations for form fields. You may not use the service to:
            </p>
            <ul className="mt-4 list-disc pl-6 space-y-2">
              <li>Attempt to reverse-engineer, abuse, or overload the API</li>
              <li>Use automated scripts to generate excessive requests beyond normal usage</li>
              <li>Resell or redistribute explanations generated by the service</li>
              <li>Violate any applicable laws or regulations</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">Subscription Terms</h2>
            <p className="mt-3">
              Fillyfy offers multiple paid plans billed monthly through Stripe:
            </p>
            <ul className="mt-4 list-disc pl-6 space-y-2">
              <li>Starter: $10/month — 15 forms per month</li>
              <li>Pro: $20/month — 50 forms per month</li>
              <li>Business: $39/month — 300 forms per month</li>
            </ul>
            <p className="mt-3">
              Your subscription renews automatically each month until cancelled. You may cancel your subscription at any time through your account settings.
            </p>
            <p className="mt-3">
              The free plan provides 1 form per calendar month at no cost. Usage resets on the 1st of each month. A &quot;form&quot; counts as one form session — clicking multiple fields within the same form does not use additional forms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">Refund Policy</h2>
            <p className="mt-3">
              We do not provide refunds for partial months of service. When you cancel your subscription, your access to Pro features continues until the end of the current billing period. After that, your account reverts to the free plan.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">Limitation of Liability</h2>
            <p className="mt-3">
              The Fillyfy service is provided &quot;as is&quot; without warranties of any kind, either express or implied. We do not guarantee:
            </p>
            <ul className="mt-4 list-disc pl-6 space-y-2">
              <li>Uninterrupted or error-free service availability</li>
              <li>Accuracy or completeness of AI-generated explanations</li>
              <li>That the service will meet your specific requirements</li>
            </ul>
            <p className="mt-4">
              In no event shall Fillyfy be liable for any indirect, incidental, special, or consequential damages arising from your use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">Account Termination</h2>
            <p className="mt-3">
              We reserve the right to suspend or terminate accounts that violate these terms, engage in abusive behavior, or attempt to circumvent usage limits. We will make reasonable efforts to notify you before termination, except in cases of severe abuse.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">Changes to Terms</h2>
            <p className="mt-3">
              We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the updated terms. We will notify users of significant changes via email.
            </p>
          </section>
        </div>

        <div className="mt-16 border-t border-gray-800 pt-8">
          <a href="/" className="text-sm text-gray-400 hover:text-white transition">
            &larr; Back to home
          </a>
        </div>
      </div>
    </main>
  );
}
